name: Run and build Application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: My code
      uses: actions/checkout@v2
    - name: Install packages
      run: pip install -t •
